defaults: &defaults
  docker:
    - image: circleci/node:10.8.0

version: 2
jobs:
    build:
      <<: *defaults
      steps:
        - checkout
        - restore_cache:
            key: dependency-cache-{{ checksum "package.json" }}
        - run:
            name: Install npm
            command: npm install
        - run:
            name: Check code quality
            command: npm run lint
        - run:
            name: Run tests
            command: node_modules/.bin/jest --runInBand --ci --reporters=jest-junit
            environment:
                JEST_JUNIT_OUTPUT: "test-results/jest/results.xml"
        - store_artifacts:
            path: test-results
        - store_test_results:
            path: test-results
        - run:
            name: Post coverage results
            command: node_modules/.bin/codecov --token=21b041e2-a6d4-4eaa-ac72-d3264fe9adbf
        - save_cache:
            key: dependency-cache-{{ checksum "package.json" }}
            paths:
              - node_modules
    semver:
        <<: *defaults
        steps:
        - checkout
        - restore_cache:
            key: dependency-cache-{{ checksum "package.json" }}
        - run:
            name: Install npm
            command: npm install
        - run:
            name: Semantic Release
            command: node_modules/.bin/semantic-release

workflows:
  version: 2
  build_test_release:
    jobs:
      - build
      - semver:
          requires:
            - build
          filters:
            branches:
              only: master